name: Build and Deploy
on:
  workflow_dispatch:
        
jobs:
  automation-tests-edge:
    name: Automation Tests Edge
    uses: ./.github/workflows/ci.yml
    secrets: inherit
    with:
      DEPLOY_ENV: "ALPHA"
      
