name: Build and Deploy
on:
  workflow_dispatch:
     inputs:
       my_parameter:
         description: 'My First param'
         required: true
        
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Clone repo
      uses: actions/checkout@v2
    - name: Waiting for a command
      run: |
        sleep 15
    - name: Random command 
      run: |
          echo "El valor del parámetro es ${{ github.event.inputs.my_parameter }}"
