name: Build and Deploy
on:
  workflow_dispatch:
        
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Clone repo
      uses: actions/checkout@v2
    - name: Waiting for a command
      run: |
        sleep 15
    - name: Random command
      run: pwd
