name: Trigger automation job

on:
  workflow_run:
    workflows: [Build and Deploy]
    types: ['completed']
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Setting branch name
      run: | 
        echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV
        echo "COMMIT=${GITHUB_REF#refs/heads/}.${GITHUB_SHA}" >> $GITHUB_ENV
        echo "APP_PREFIX=therapist" >> $GITHUB_ENV
        if [[ $APP_PREFIX = "therapist" ]]; then
            EVENT_TYPE = "ios-therapist-tests
        else
            EVENT_TYPE = "ios-patient-tests
        fi
        
    - name: Triggering automation tests
      run: |
        response=$(curl --silent --write-out '%{http_code}'\
          -X POST \
          -H "Accept: application/vnd.github.everest-preview+json" \
          -H "Authorization: Bearer ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}" \
          https://api.github.com/repos/rjvargasc/github-triggered/dispatches \
          -d '{"event_type": "'$EVENT_TYPE'", "client_payload":{"branch":"${{env.BRANCH}}", "commit":"${{env.COMMIT}}"}}')
        echo "response = $response"
        if ! grep -q "204" <<< "$response"; then
          echo "There was and error triggering automated tests for the web"
          exit 1
        fi
