name: Trigger automation job

on:
  workflow_run:
    workflows: [Build and Deploy]
    types: ['completed']
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: display branch
      run: echo ${{ github.ref }}
    - name: Trigger other repository
      run: |
        curl \
          -X POST \
          -H "Accept: application/vnd.github.everest-preview+json" \
          -H "Authorization: Bearer ${{ secrets.MY_PAT_TOKEN }}" \
          https://api.github.com/repos/lunacare/automation/dispatches \
          -d '{"event_type": "web-tests", "client_payload":{"environment":"${{ github.ref }}"}}'
