name: Trigger automation job

on:
  workflow_run:
    workflows: [Build and Deploy]
    types: ['completed']
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Setting branch name
      run: echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV

    - name: Trigger other repository
      run: |
        curl \
          -X POST \
          -H "Accept: application/vnd.github.everest-preview+json" \
          -H "Authorization: Bearer ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}" \
          https://api.github.com/repos/lunacare/automation/dispatches \
          -d '{"event_type": "web-tests", "client_payload":{"environment":"${{env.BRANCH}}"}}'
