name: Trigger automation job

on:
  workflow_run:
    workflows: [Build and Deploy]
    types: ['completed']
    
env:
  EVENT_TYPE : "web-tests-beta"  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Setting branch name
      run: | 
        echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV
        echo "COMMIT=${GITHUB_REF#refs/heads/}.${GITHUB_SHA}" >> $GITHUB_ENV

    - name: Setting environment variable
      run: |     
        if [[ ${{env.BRANCH == "main"}} ]]; then
            echo "EVENT_TYPE=web-tests-alpha" >> $GITHUB_ENV
            exit 0
        fi    
      
    - name: display event type variable v1
      run: echo "este es valor 1 $EVENT_TYPE"
      
    - name: Setting environment variable v2
      if: $BRANCH == 'main'
      run: echo "EVENT_TYPE2=web-tests-alpha" >> $GITHUB_ENV
      
    - name: display event type variable v2
      run: echo "este es valor 2 $EVENT_TYPE2"
      
    - name: Triggering automation tests
      run: |
        response=$(curl --silent --write-out '%{http_code}'\
          -X POST \
          -H "Accept: application/vnd.github.everest-preview+json" \
          -H "Authorization: Bearer ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}" \
          https://api.github.com/repos/rjvargasc/github-triggered/dispatches \
          -d '{"event_type": "${{env.EVENT_TYPE}}", "client_payload":{"branch":"${{env.BRANCH}}", "commit":"${{env.COMMIT}}"}}')
        echo "response = $response"
        if ! grep -q "204" <<< "$response"; then
          echo "There was and error triggering automated tests for the web"
          exit 1
        fi
